# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/GameEvent.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto import CatchEvent_pb2 as proto_dot_CatchEvent__pb2
from proto import LocationEvent_pb2 as proto_dot_LocationEvent__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/GameEvent.proto',
  package='ch.epfl.sdp.game.comm',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x15proto/GameEvent.proto\x12\x15\x63h.epfl.sdp.game.comm\x1a\x16proto/CatchEvent.proto\x1a\x19proto/LocationEvent.proto\"\xa3\x01\n\tGameEvent\x12\x11\n\ttimestamp\x18\x01 \x01(\x07\x12\x38\n\x0b\x63\x61tch_event\x18\n \x01(\x0b\x32!.ch.epfl.sdp.game.comm.CatchEventH\x00\x12>\n\x0elocation_event\x18\x0b \x01(\x0b\x32$.ch.epfl.sdp.game.comm.LocationEventH\x00\x42\t\n\x07payloadb\x06proto3'
  ,
  dependencies=[proto_dot_CatchEvent__pb2.DESCRIPTOR,proto_dot_LocationEvent__pb2.DESCRIPTOR,])




_GAMEEVENT = _descriptor.Descriptor(
  name='GameEvent',
  full_name='ch.epfl.sdp.game.comm.GameEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='ch.epfl.sdp.game.comm.GameEvent.timestamp', index=0,
      number=1, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='catch_event', full_name='ch.epfl.sdp.game.comm.GameEvent.catch_event', index=1,
      number=10, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='location_event', full_name='ch.epfl.sdp.game.comm.GameEvent.location_event', index=2,
      number=11, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='payload', full_name='ch.epfl.sdp.game.comm.GameEvent.payload',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=100,
  serialized_end=263,
)

_GAMEEVENT.fields_by_name['catch_event'].message_type = proto_dot_CatchEvent__pb2._CATCHEVENT
_GAMEEVENT.fields_by_name['location_event'].message_type = proto_dot_LocationEvent__pb2._LOCATIONEVENT
_GAMEEVENT.oneofs_by_name['payload'].fields.append(
  _GAMEEVENT.fields_by_name['catch_event'])
_GAMEEVENT.fields_by_name['catch_event'].containing_oneof = _GAMEEVENT.oneofs_by_name['payload']
_GAMEEVENT.oneofs_by_name['payload'].fields.append(
  _GAMEEVENT.fields_by_name['location_event'])
_GAMEEVENT.fields_by_name['location_event'].containing_oneof = _GAMEEVENT.oneofs_by_name['payload']
DESCRIPTOR.message_types_by_name['GameEvent'] = _GAMEEVENT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GameEvent = _reflection.GeneratedProtocolMessageType('GameEvent', (_message.Message,), {
  'DESCRIPTOR' : _GAMEEVENT,
  '__module__' : 'proto.GameEvent_pb2'
  # @@protoc_insertion_point(class_scope:ch.epfl.sdp.game.comm.GameEvent)
  })
_sym_db.RegisterMessage(GameEvent)


# @@protoc_insertion_point(module_scope)
