# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/LocationEvent.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto import Location_pb2 as proto_dot_Location__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/LocationEvent.proto',
  package='ch.epfl.sdp.game.comm',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x19proto/LocationEvent.proto\x12\x15\x63h.epfl.sdp.game.comm\x1a\x14proto/Location.proto\"T\n\rLocationEvent\x12\x10\n\x08playerID\x18\x01 \x01(\x05\x12\x31\n\x08location\x18\x02 \x01(\x0b\x32\x1f.ch.epfl.sdp.game.comm.Locationb\x06proto3'
  ,
  dependencies=[proto_dot_Location__pb2.DESCRIPTOR,])




_LOCATIONEVENT = _descriptor.Descriptor(
  name='LocationEvent',
  full_name='ch.epfl.sdp.game.comm.LocationEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='playerID', full_name='ch.epfl.sdp.game.comm.LocationEvent.playerID', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='location', full_name='ch.epfl.sdp.game.comm.LocationEvent.location', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=74,
  serialized_end=158,
)

_LOCATIONEVENT.fields_by_name['location'].message_type = proto_dot_Location__pb2._LOCATION
DESCRIPTOR.message_types_by_name['LocationEvent'] = _LOCATIONEVENT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LocationEvent = _reflection.GeneratedProtocolMessageType('LocationEvent', (_message.Message,), {
  'DESCRIPTOR' : _LOCATIONEVENT,
  '__module__' : 'proto.LocationEvent_pb2'
  # @@protoc_insertion_point(class_scope:ch.epfl.sdp.game.comm.LocationEvent)
  })
_sym_db.RegisterMessage(LocationEvent)


# @@protoc_insertion_point(module_scope)
